Blog/urls.py
from django.contrib import admin
from django.urls import path,include


from django.contrib.auth.models import User, Group
from django.apps import apps  # To get all models
from django_otp.admin import OTPAdminSite
import os
# from django_otp.plugins.otp_totp.models import TOTPDevice
# from django_otp.plugins.otp_totp.admin import TOTPDeviceAdmin
 
 
# Create a custom OTPAdmin site
class OTPAdmin(OTPAdminSite):
    pass

# Create an instance of the custom admin site
admin_site = OTPAdmin(name="OTPAdmin")

models = apps.get_models()
for model in models:
    try:
        admin_site.register(model)
    except admin.sites.AlreadyRegistered:
        pass
 
 

if os.getenv('VERCEL_ENV') is None:
    from dotenv import load_dotenv
    load_dotenv()
    
admin_url = os.getenv('ADMIN_URL', 'WrongUrlBuddy.')



urlpatterns = [
    path('',include('blogs.urls')),
    path('accounts/',include('accounts.urls')),
    path(f'{admin_url}/', admin_site.urls),  
]

accounts/urls.py
from django.urls import path,include
from .views import CustomLoginView

app_name='accounts'
from . import views

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),  # Use the custom login view
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name='register'),
]

blogs/urls.py
from django.urls import path
from . import views

app_name='blogs'
# **app_name** is a predefined variable in Django that
# the framework uses specifically to recognize the namespace for
# URL patterns in an app. It must be spelled exactly as app_name,
# and any variations like app_names, appname, or appnames will not work.

urlpatterns = [
    path('',views.home,name='home'),
    path('blogs/',views.all_blogs,name='all_blogs'),
    path('blogs/<int:blog_id>',views.blog,name='blogs'),
    path('posts/',views.posts,name='posts'),
    path('add_blogs/',views.new_blogs,name='new_blogs'),
    path('add_posts/<int:blog_id>',views.new_posts,name='new_posts'),
    path('edit_posts/<int:post_id>',views.edit_posts,name='edit_posts'),

    path('user_posts/<str:username>/', views.user_posts, name='user_posts'),
    # path('toggle_like/', views.toggle_like, name='toggle_like'),

]

blogs/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class blog_name(models.Model):
    """A blog which user wants to read"""
    b_name=models.CharField(max_length=100)
    date=models.DateTimeField(auto_now_add=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE) # Connecting data to certain users. Still other logged in users can access other peoples data through url.
    
    def __str__(self):
        if len(self.b_name)>30:
            return f'{self.b_name[:30]}...'
        else:
            return f"{self.b_name}" 

class blog_post(models.Model): # if forgot models.Model then app won't makemigrations.
    f_key=models.ForeignKey(blog_name,on_delete=models.CASCADE)
    post_name=models.CharField(max_length=150)
    post=models.TextField()
    post_date=models.DateTimeField(auto_now_add=True)
    
    #auto_now takes precedence (obviously, because it updates field each time, while auto_now_add updates on creation only.
    # So making last_modified as auto_now_add Does not automatically update time on each save. But rather updates on creation(new entry is created when change is detected) only.
    
    
    def __str__(self):
        if len(self.post_name)>70:
            return f"{self.post_name[:70]}..."
        else:
            return f"{self.post_name}" 

blogs/forms.py
from django import forms
from .models import blog_name,blog_post


class BlogForm(forms.ModelForm):
    class Meta:
# The Meta class is a special inner class where you define options for the
# model or form, such as verbose_name, ordering, fields, and more. Django looks
# for this class specifically to apply those options.
# So, while it can technically be named differently, it's best practice to use
# Meta to maintain consistency and clarity in your code.
        
        
        
# The fields attribute in the Meta class of a Django form specifies which
# fields from the model should be included in the form.
# For example, if your model has name, description, and date, and you only want name and description
        model = blog_name
        fields = ['b_name'] # What you want to include in the form from your Model.py
        labels = {'b_name': ''} 
        
class PostForm(forms.ModelForm):
    class Meta:
        model = blog_post
        fields = ['post_name','post']
        labels = {'post_name': 'Post Title:'}
        widgets = {'post': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render,redirect
from .forms import BlogForm,PostForm

# Create your views here.
from .models import blog_name,blog_post
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.views.decorators.cache import never_cache

from .serializers import BlogSerializers,PostSerializers
from rest_framework.decorators import api_view
from rest_framework.response import Response

def home(request):
    return render(request,"blogs/home.html")

@login_required # TO make it work add login_url in settings
@never_cache
# @ can help only authentic users to browse data. but authentic users can browse other users data too.

@api_view(['GET'])
def all_blogs(request):
    """Show all blogs."""
    name=blog_name.objects.filter(user=request.user) # left user is a foreign key.
    #tells Django to retrieve only the blog objects from the database whose user attribute matches the current user. We just add the ownership of data to each user. Protecting it is still left.
    # serializer=BlogSerializers(name, many=True)
    context={'blog_names':name} # Creating API not a webpage, Hence no need the context dict. 
    return render(request,'blogs/blogs.html',context)
    # return Response(serializer.data) # Creating API for all_blogs data to be consumed by Vue.

@login_required
@never_cache

@api_view(['GET','POST'])
def blog(request,blog_id):
    """Show posts of clicked blog"""
    try:
        name=blog_name.objects.get(id=blog_id)
    except blog_name.DoesNotExist:
        raise Http404("404 not found")

    
    #Make sure the blogs belongs to current user.
    # if name.user != request.user: # Means if blog_name is not owned by current user.
    #     raise Http404
    check_blog_owner(request,name)
    
    
    post=blog_post.objects.filter(f_key=name)
    # context={'blog_name':name,'post_name':post}
    # return render(request,'blogs/blog.html',context)

    B_serializer=BlogSerializers(name) # we retrieve a single blog instance using name = blog_name.objects.get(id=blog_id). This means that the variable name holds just one blog_name object.
    P_serializer=PostSerializers(post,many=True)
    
    return Response({       #Response() you can only pass one argument for the main data, so if you try Response(B_serializer.data, P_serializer.data), it will raise an error because it doesn’t support multiple data arguments.
        'blog':B_serializer.data,
        'post':P_serializer.data
    })

from django.db.models import Count
from django.shortcuts import render

@api_view(['GET'])
def posts(request):
    # Use a queryset with annotations to count posts per author and filter for those with more than 3 posts
    if request.user.is_authenticated:
        # Get all posts, ordering by post_date, and annotating to count posts per user
        all_posts = (
            blog_post.objects
            .select_related('f_key')  # Use select_related for f_key to reduce queries
            .prefetch_related('f_key__user')  # Prefetch related user objects for efficiency
            .order_by('-post_date')
        )
    else:
        all_posts = blog_post.objects.select_related('f_key').order_by('-post_date')

    # Create a dictionary where the key is the username, and the value is a list of up to 3 posts
    posts_by_author = {}
    
    # Limit to 3 posts per author directly while iterating
    for post in all_posts:
        author = post.f_key.user.username
        if author not in posts_by_author:
            posts_by_author[author] = []
        if len(posts_by_author[author]) < 3:
            posts_by_author[author].append(post)

    # Get authors with more than 3 posts
    authors_with_more_posts = (
        blog_post.objects
        .values('f_key__user__username')
        .annotate(post_count=Count('id'))
        .filter(post_count__gt=3)
    # The __gt lookup stands for "greater than," so post_count__gt=3 filters out only those results where the post_count is greater than 3.
    # This means it will return only the authors who have more than 3 blog posts.
    )

    allPosts_serializer=PostSerializers(all_posts, many=True)
    # author_serializer=PostSerializers(authors_with_more_posts)
    
    return Response({
        'allPosts':allPosts_serializer.data,
        'More_posts':authors_with_more_posts,
        'author':author,
    })

    # context = {
    #     'posts_by_author': posts_by_author,
    #     'authors_with_more_posts': [author['f_key__user__username'] for author in authors_with_more_posts],
    #     'owner': request.user
    # }
    # return render(request, 'blogs/posts.html', context)


@login_required
@never_cache

@api_view(['GET','POST'])
def new_blogs(request):
    """Add a new blog."""
    
    if request.method == 'GET':
        # Create an empty instance of the form to represent the fields needed for creating a new blog
        empty_form = BlogForm()
        empty_form_data = {field.name: '' for field in empty_form} #loop through all the fields which lies under the BlogForm() form. And we also use {} here, means we converted this into JSON, so need of serialization. 
        # field.name refers to the name attribute of a field defined in the BlogForm. Each field in a Django form is an instance of a Field class (such as CharField, TextField, etc.), and each of these instances has a name property. This property corresponds to the name of the field as specified when the form was defined.
        return Response(empty_form_data)  # Return serialized data as JSON
    elif request.method=='POST':
        form = BlogForm(data=request.data)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.user = request.user  # Assign the blog to the current user
            new_blog.save()
            
            new_blog_serializer = BlogSerializers(new_blog)
            return Response(new_blog_serializer.data, status=201)  # Successful creation
    
        # If form is invalid, return form errors
        return Response(form.errors, status=400)    

@login_required
@never_cache
@api_view(['GET', 'POST'])
def new_posts(request, blog_id):
    """View to retrieve or add posts to a specific blog."""
    
    try:
        blog = blog_name.objects.get(id=blog_id)
    except blog_name.DoesNotExist:
        return Response({"error": "Blog not found"}, status=404)
    
    if request.method == 'GET':
        # Fetch and serialize posts related to the blog
        posts = blog_post.objects.filter(f_key=blog)
        serializer = PostSerializers(posts, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        # Attach the blog as the foreign key and validate input data
        serializer = PostSerializers(data=request.data)
        if serializer.is_valid():
            # Manually set the foreign key to the blog instance
            serializer.save(f_key=blog)
            return Response(serializer.data, status=201)
        else:
            # If data is invalid, return errors
            return Response(serializer.errors, status=400)
        
        
        # Create post instance without saving to the database
        # Set the foreign key to the blog instance
        # Now save the post to the database
                
#        return redirect('blogs:blogs',blog_id) 
    # or you can "return redirect('blogs:new_posts',blog_id)"
#     context={'form':form,'blog_name': blog}
#     return render(request,'blogs/new_posts.html',context)


from django.utils import timezone
@login_required
@never_cache

@api_view(['GET','POST'])
def edit_posts(request, post_id):
    
    """Edit an existing entry."""
    try:
        post = blog_post.objects.get(id=post_id)
        f_key = post.f_key #it gives the 'blog_name' instance that the post is linked to.
    # the left f_key is now a blog object instance. We could name it anything. 
    except blog_post.DoesNotExist:
        raise Http404("404 not found")
    
    
    # if f_key.user != request.user: #f_key.user literally means blog.user. We check whether the user/owner of the blog matches the currently logged-in user. raise Http404
    
    check_blog_owner(request,f_key)
    
    
    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
#        form = PostForm(instance=post)
        serializer=PostSerializers(post)
        return Response(serializer.data)
    else:
        serializer=PostSerializers(post, data=request.data)
        if serializer.is_valid():
            if serializer.initial_data != serializer.validated_data:  # same as if form.has_changed()
                post.post_date=timezone.now()   # Update only even if any one field changes.

    # Manually set the foreign key to the blog instance
            serializer.save(f_key=f_key)
            return Response(serializer.data, status=201)
        else:
            # If data is invalid, return errors
            return Response(serializer.errors, status=400)

                            # PREVIOUS CODE:
        # POST data submitted; process data.
#       form = PostForm(instance=post, data=request.POST)
#        if form.is_valid():
#            if form.has_changed():  # Check if any fields were actually changed
#                post.post_date = timezone.now()  # Update only if changes were made
#            form.save()
#            return redirect('blogs:blogs', f_key.id)
#    context = {'post': post, 'blog': f_key, 'form': form}
#    return render(request, 'blogs/edit_posts.html', context)

@api_view(['GET'])
def user_posts(request, username):
    # Fetch all posts for the specified author based on `blog_name`
    user_posts = blog_post.objects.filter(f_key__user__username=username).order_by('-post_date')
    
    serializer=PostSerializers(user_posts ,many=True)
    return Response(serializer.data)
    # context = {'user_posts': user_posts, 'author': username}
    # return render(request, 'blogs/user_posts.html', context)

blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bloggy</title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">

            <a class="navbar-brand" href="{%url 'blogs:home' %}">Bloggy Home</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {%if user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'blogs:all_blogs' %}">My Blogs</a>
                    </li>
                    {%endif%}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'blogs:posts' %}">All Posts</a>
                    </li>
                </ul>




                <ul class="navbar-nav ms-auto mb-2 mb-md-0"> <!--ms-auto means margin start automatic-->
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text me-2">Hello, {{ user.username }}.
                        </span>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:register' %}">
                            Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">
                            Log in</a>
                    </li>
                    {% endif %}
                </ul> <!-- End of account-related links -->


                {% if user.is_authenticated %}
                <form action="{% url 'accounts:logout' %}" method='post'>
                    {% csrf_token %}
                    <button name='submit' class='btn btn-outline-secondary btn-sm'>
                        Log out</button>
                </form>
                {% endif %}







            </div>
        </div>
    </nav>

    <main class="container">
        <div class="pb-2 mb-2 border-bottom"> <!--pb means padding bottom, mb means margin bottom-->
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>

</body>

</html>

blogs/templates/blogs/blog.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}
{% block content %}










<h1>
    {{blog_name.b_name}}
</h1>

<h3>
    <a href="{%url 'blogs:new_posts' blog_name.id %}">
        Create a new post
    </a>
</h3>


<ul>
    {%for x in post_name%}

    <div class="card mb-3" style="border: none; border-radius: 0.5rem; overflow: hidden;">
        <!-- Card header with timestamp and edit link -->
        <div class="card-header"
            style="background-color: #343a40; color: white; padding: 1rem; display: flex; justify-content: space-between; align-items: center;">
            <h5 class="mb-0" style="font-size: 1.2rem;">{{ x.post_date|date:'D, d M Y, h:i A' }}</h5>
            <small>
                <a href="{% url 'blogs:edit_posts' x.id %}"
                    style="color: #61dafb; text-decoration: none; transition: color 0.3s;">
                    edit entry
                </a>
            </small>
        </div>
        <div class="card-body" style="background-color: #f4f4f4; padding: 1.5rem;">
            <h6 class="fw-bold" style="margin-bottom: 0.5rem; color: #333;">{{ x.post_name|linebreaks }}</h6>
            <p style="color: #666; line-height: 1.5;">{{ x.post|linebreaks }}</p>
        </div>
    </div>
    {%endfor%}
</ul>

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}

{% block content %}
<div class="p-4 mb-5" style="background-color: #f0f8ff; border: 1px solid #c4e3ff; border-radius: .5rem;">
    <div class="container-fluid text-center py-3">
        <h1 class="display-7 fw-bold" style="color: #003366;">Welcome to Your Blog Dashboard</h1>
        <!-- Subtle, professional color -->
        <p class="lead" style="color: #004080;">Easily create and manage your blogs. Start by adding a new blog, then
            share your posts with the world.</p>
    </div>
</div>

<ul>
    {%for x in blog_names%}
    <h3>
        <li>
            <a href="{% url 'blogs:blogs' x.id%}">
                {{x}}
            </a>
        </li>
    </h3>
    {%endfor%}
</ul>
<a href="{%url 'blogs:new_blogs'%}" style="padding-bottom: 10%;">Add New Blog</a>
{% endblock content %}

blogs/templates/blogs/edit_posts.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}
{% block content %}

<h2> Blog name:
    <a href="{% url 'blogs:blogs' blog.id %}">
        {{blog.b_name}}
    </a>
</h2>
<form action="{% url 'blogs:edit_posts' post.id %}" method='post'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Save changes" %}
</form>
{% endblock content %}

blogs/templates/blogs/home.html
{% extends 'blogs/base.html'%}



{% comment %} 

Here block tags will match their name 'content' with base.html block tags, and 
figures what not to inherit.

{% endcomment %}
{% block page_header %}
  <div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4"> <!--py means padding in top,bottom. y axis.-->

       <h1 class="display-3">Bloggy.</h1>
       <p class="lead">Start your own blog to share your thoughts and insights on topics that are important to you. With each post, you have the opportunity to express your ideas and engage with the community by discovering what others have shared.</p>
       {%if not user.is_authenticated%}
       <a class="btn btn-primary btn-lg mt-1"
        href="{% url 'accounts:register' %}">Register &raquo;</a> <!--&raquo actually writes '>>'-->
        {%endif%}
       {%if user.is_authenticated%}
       <a class="btn btn-primary btn-lg mt-1"
        href="{% url 'blogs:all_blogs' %}">Create your blog now &raquo;</a> <!--&raquo actually writes '>>'-->
        {%endif%}
    </div>
  </div>
 {% endblock page_header %}

blogs/templates/blogs/new_blogs.html
{%extends 'blogs/base.html'%}
{% load django_bootstrap5 %}


{%block content%}
<h3> Write Blog Title! </h3>


<form action="{%url 'blogs:new_blogs'%}" method="post">
    {%csrf_token%}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add Blog" %}
</form>

{% endblock content %}

blogs/templates/blogs/new_posts.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block page_header %}


<div class="p-5 mb-5"
    style="background-color: #f0f8ff; border: 1px solid #d1e7dd; border-radius: .5rem; box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);">
    <div class="container-fluid text-center">
        <h1 class="display-6 fw-bold" style="color: #003366;">Sharing with Purpose</h1>
        <p class="lead" style="color: #333;">
            We’re excited to have you share your thoughts and experiences here. Just a heads-up: once
            you post something,<span class="fw-semibold" style="color: #003366;"> your thoughts will forever remain
                visible to everyone and stays on the site.</span>
            We encourage you to think
            carefully about what you share, as your words contribute to our community’s atmosphere. Let’s work together
            to make Bloggy a positive and welcoming space for all!
        </p>
    </div>
</div>


<h3> Add New Post for ' {{blog_name.b_name}} ' </h3>


{%endblock page_header%}

{% block content %}


<form action="{%url 'blogs:new_posts' blog_name.id %} " method="post" class="mb-4">
    {%csrf_token%}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Share this post" %}
</form>


{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block content %}
<div class="p-3 mb-4" style="background-color: #f0f8ff; border: 1px solid #c4e3ff; border-radius: .5rem;">

    <div class="container-fluid text-center py-4">
        <h5 class="display-6 fw-bold" style="color: #003366;">Welcome to the Community Posts!</h5>
        <p class="lead" style="color: #004080;">Browse through posts shared by others, or login to create your own to
            join the conversation.
        </p>
    </div>
</div>

{% for author, posts in posts_by_author.items %}
<div class="mb-4"
    style="padding: 1.5rem; background-color: #ffffff; border-radius: 0.5rem; box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);">
    <span class="fw-bold" style="font-size: 1.7rem; color: #0056b3;">{{ author }}'s Posts</span>
    {% if author == owner.username %}
    <span style="font-weight: 400; color: #777;"> (You) </span>
    {% endif %}

    <ul class="list-group" style="border-radius: 0.5rem; overflow: hidden; margin-top: 1rem;">
        {% for post in posts %}
        <li class="list-group-item"
            style="border: none; background-color: #f9f9f9; padding: 1.5rem; border-bottom: 1px solid #e0e0e0;">
            <h6 class="fw-bold" style="color: #333; margin-bottom: 0.5rem;">{{ post.post_name }}</h6>
            <p style="color: #555; line-height: 1.6;">{{ post.post|linebreaks }}</p>
            <p style="float:right; font-size: 0.85rem; color: #999;">{{ post.post_date|date:'D, d M Y. h:i A' }}</p>
        </li>
        {% endfor %}
    </ul>

    {% if author in authors_with_more_posts %}
    <div class="mt-3">
        <a href="{% url 'blogs:user_posts' author %}" class="btn btn-link"
            style="color: #0056b3; text-decoration: none; font-weight: 500; transition: color 0.3s;">
            Read more posts from {{ author }}
        </a>
    </div>
    {% endif %}
</div>
{% endfor %}


{% if owner.username not in posts_by_author and user.is_authenticated %}
<div class="mb-4"
    style="padding: 2rem; background: #fff3e6; border-radius: 15px; text-align: center;box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);">
    <h5 style="color: #ff6347; margin-bottom: .6rem;">
        ☕ Let's Brew Some Ideas! ☕
    </h5>
    <p style="font-size: .9rem; color: #444;">
        You haven’t shared any thoughts yet.
        Grab a cup of tea and start writing!
    </p>
    <a href="{% url 'blogs:all_blogs' %}" class="btn btn-danger"
        style="color: #ffffff; background-color: #ff6347; padding: 0.75rem 1.5rem; border-radius: 0.5rem; text-decoration: none; font-size: .9rem;">
        Start Your Post
    </a>
</div>
{% endif %}




<script>
    // Store scroll position before navigating to user_posts
    function storeScrollPosition() {
        sessionStorage.setItem('scrollPosition', window.scrollY);
    }

    // Restore scroll position when loading the posts page
    function restoreScrollPosition() {
        const scrollPosition = sessionStorage.getItem('scrollPosition');
        if (scrollPosition) {
            window.scrollTo(0, parseInt(scrollPosition, 10));
            sessionStorage.removeItem('scrollPosition'); // Clear the position after use
        }
    }

    // Attach the function to the "Read more posts" link
    document.addEventListener("DOMContentLoaded", function () {
        const readMoreLinks = document.querySelectorAll("a.btn-link"); // Assuming these are your links
        readMoreLinks.forEach(link => {
            link.addEventListener("click", storeScrollPosition);
        });

        restoreScrollPosition(); // Restore position when the page loads
    });
</script>





{% endblock content %}

blogs/templates/blogs/user_posts.html
{% extends "blogs/base.html" %}
{% load django_bootstrap5 %}

{% block content %}

<div class="p-3 mb-4" style="background-color: #eaf4fc; border: 1px solid #d5ecff; border-radius: .5rem;">
    <div class="container-fluid text-center py-4">
        <h5 class="display-6 fw-bold" style="color: #003366;">{{ author }}'s Posts</h5>
        <p class="lead">Here are the posts shared by {{ author }}.</p>
    </div>
</div>

<div class="mb-4"
    style="padding: 1.5rem; background-color: #ffffff; border-radius: 0.5rem; box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);">
    <ul class="list-group" style="border-radius: 0.5rem; overflow: hidden;">
        {% for post in user_posts %}
        <li class="list-group-item"
            style="border: none; background-color: #f9f9f9; padding: 1.5rem; border-bottom: 1px solid #e0e0e0;">
            <h6 class="fw-bold" style="color: #333; margin-bottom: 0.5rem;">{{ post.post_name }}</h6>
            <p style="color: #555; line-height: 1.6;">{{ post.post|linebreaks }}</p>
            <p style="float:right; font-size: 0.85rem; color: #999;">{{ post.post_date|date:'D, d M Y. h:i A' }}</p>
        </li>
        {% endfor %}
    </ul>

    <div class="mt-3 text-center">
        <a href="{% url 'blogs:posts' %}" class="btn btn-link"
            style="color: #0056b3; text-decoration: none; font-weight: 500; transition: color 0.3s;">
            Back to All Posts
        </a>
    </div>
</div>

{% endblock content %}